// Generated by https://quicktype.io

// export interface CoronaData {
//     summaryStats:  SummaryStats;
//     cache:         Cache;
//     dataSource:    DataSource;
//     apiSourceCode: string;
//     rawData:       RawDatum[];
// }

// export interface Cache {
//     lastUpdated:          string;
//     expires:              string;
//     lastUpdatedTimestamp: number;
//     expiresTimestamp:     number;
// }

// export interface DataSource {
//     url:              string;
//     lastGithubCommit: string;
//     publishedBy:      string;
//     ref:              string;
// }

// export interface RawDatum {
//     "Province/State": string;
//     "Country/Region": string;
//     "Last Update":    string;
//     Confirmed:        string;
//     Deaths:           string;
//     Recovered:        string;
//     Latitude:         string;
//     Longitude:        string;
// }

export interface groupData {
    Iso2: string;
    Confirmed: number;
    Recovered: number;
    Deaths: number;
    RecoveryInPercent?: string;
    colorValue?: string;
    Data: CoronaData[];
}

export interface MapData {
    Confirmed: number;
    Deaths: number;
    Recovered: number;
    RecoveryInPercent: string;
    colorValue: string;
}

// export interface SummaryStats {
//     global:   China;
//     china:    China;
//     nonChina: China;
// }

// export interface China {
//     confirmed: number;
//     recovered: number;
//     deaths:    number;
// }


// Generated by https://quicktype.io

// export interface CoronaData {
//     latest:    Latest;
//     locations: Location[];
// }

// export interface Latest {
//     confirmed: number;
//     deaths:    number;
//     recovered: number;
// }

// export interface Location {
//     coordinates:  Coordinates;
//     country:      string;
//     country_code: string;
//     id:           number;
//     last_updated: string;
//     latest:       Latest;
//     province:     string;
// }

// export interface Coordinates {
//     latitude:  string;
//     longitude: string;
// }


// Generated by https://quicktype.io

export interface CoronaData {
    country:            string;
    countryInfo:        CountryInfo;
    cases:              number;
    todayCases:         number;
    deaths:             number;
    todayDeaths:        number;
    recovered:          number;
    active:             number;
    critical:           number;
    casesPerOneMillion: number;
}

export interface CountryInfo {
    iso2: string;
    iso3: string;
    _id:  IDEnum | number;
    lat:  number;
    long: number;
    flag: string;
}

export enum IDEnum {
    NoData = "NO DATA",
}
