// Generated by https://quicktype.io

export interface CoronaData {
    summaryStats:  SummaryStats;
    cache:         Cache;
    dataSource:    DataSource;
    apiSourceCode: string;
    rawData:       RawDatum[];
}

export interface Cache {
    lastUpdated:          string;
    expires:              string;
    lastUpdatedTimestamp: number;
    expiresTimestamp:     number;
}

export interface DataSource {
    url:              string;
    lastGithubCommit: string;
    publishedBy:      string;
    ref:              string;
}

export interface RawDatum {
    "Province/State": string;
    "Country/Region": string;
    "Last Update":    string;
    Confirmed:        string;
    Deaths:           string;
    Recovered:        string;
    Latitude:         string;
    Longitude:        string;
}

export interface groupData {
    Country: string;
    Confirmed: number;
    Recovered: number;
    Deaths: number;
    RecoveryInPercent?: string;
    colorValue?: string;
    Data: RawDatum[];
}

export interface MapData {
    Confirmed: number;
    Deaths: number;
    Recovered: number;
    RecoveryInPercent: string;
    colorValue: string;
}

export interface SummaryStats {
    global:   China;
    china:    China;
    nonChina: China;
}

export interface China {
    confirmed: number;
    recovered: number;
    deaths:    number;
}
